version: '3.7'

volumes:
  cafe-db:

services:
  cafe-postgres:
    container_name: cafe-db
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: cafe-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - cafe-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-cafe-postgres:
    container_name: test-cafe-db
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: test-cafe-db
    volumes:
      - ./empty_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5536:5432"